baseURL = 'http://soffice.blog/'
languageCode = 'en-us'
title = 'Soft Blog'

[module]
  [[module.imports]]
    path = "github.com/adityatelange/hugo-PaperMod"

[markup.goldmark.renderer]
  unsafe = true
